### PR TITLE
Upload my course (text slides & notebooks)

### PR DESCRIPTION
**Pull request by mrpeerat**
- Upload slides
- Upload notebook
- Update readme

### CODE REVIEW

**Comment by cstorm125** [comment]
1. Upload slides as pdf to `notebooks` folder
2. Fix library versions such as pyThainlp
3. Use `-q` flag for installation to avoid boilerplate outputs
4. Add `Open in Colab` badge; make sure everything runs on Colab
5. Change notebook texts to Thai; images are ok in English
6. [Optional] QA and MT in Thai? [QA notebook](https://github.com/vistec-AI/thai2transformers/blob/dev/notebooks/train_question_answering_lm_finetuning.ipynb) and [th-zh MT](https://github.com/LalitaDeelert/lalita-mt-zhth)

**Comment by mrpeerat** [comment]
I just update slides and notebooks following your comments, please recheck.

**Comment by cstorm125** [comment]
Great work. Some more comments:
- Trusting you that all notebooks can run on Colab
- Open in Colab should point to the notebooks in this repo (the url after merge)
- Should we upload slides at pdf in case people do not have MS Office for pptx?
- Notebooks are great. No time to include Wangchanberta on QA or our MT?

Other minor edits

- `04n_nlp_intro.pptx` slide 5 is still in English
- from slide 10, the title `ตัดคำ ตัดพยางค์ แล้วทำ Bag-of-Word` has line overflow
- `05n_nlp_finetuning_part1.pptx` slide 15, should we show some benchmarks that GPT3 isn't that great?

**Comment by mrpeerat** [comment]
Done:
- Add Colab button (funny mistake haha)
- Add .pdf (delete .pptx)
- Add WangchanBERTa on Thai QA (as a extra question)
- Fix slides

Changes:
- Delete GPT-3 because we are data-centric, not model-centric (jk); I can't find anything special in GPT-3, and students cant play with it (id-pw require)
- TH-ZH's repo is not organized; I suggest refactoring the notebook repo (i.e., why you have 2 benchmark and training notebooks)

**Comment by cstorm125** [comment]
LGTM. Merging.

**Pull request merged**
